name: Initial Java CI

on: [push]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  junit-server:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Get dependencies
      - name: Install dependencies
        run: bash setup_lib.sh

     ## Build everything
     #- name: Make
     #  run: make

     ## Run unit test
     #- name: Run unit test
     #  run: make test

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Builds everything (including running unit tests)
      - name: Execute Gradle build
        run: ./gradlew build

      # report the results
      - name: Publish Test Resport
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true
          include_passed: true

  junit-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Get dependencies
      - name: Install dependencies
        run: bash setup_lib.sh

      # Build everything
      - name: Make
        run: make

      # Run unit test
      - name: Run unit test
        run: make servertest
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Get dependencies
      - name: Install dependencies
        run: bash setup_lib.sh

      # Lint 
      - name: Lint 
        run: make lint

